version: 2
registries:
  maven-google:
    type: maven-repository
    url: https://dl.google.com/dl/android/maven2/
  maven-jitpack:
    type: maven-repository
    url: https://jitpack.io
    password: dummy
    username: dummy
  gradle-plugin:
    type: maven-repository
    url: https://plugins.gradle.org/m2/

updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: "daily"
    registries: "*"
    groups:
      maven-dependencies:
        patterns:
          - "*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      maven-dependencies:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: "modules/web"
    schedule:
      interval: "daily"
    groups:
      maven-dependencies:
        patterns:
          - "*"